//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneOA
    {
        public int OAId { get; set; }
        public string AvoidObst { get; set; }
        public string AirportLimit { get; set; }
        public string GroundForceLanding { get; set; }
        public string VertAirportLimit { get; set; }
    
        public virtual DroneLogEntry DroneLogEntry { get; set; }
    }
}
