//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneRTKData
    {
        public int RTKDataId { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<double> LonP { get; set; }
        public Nullable<double> LatP { get; set; }
        public Nullable<double> HmslP { get; set; }
        public Nullable<double> LonS { get; set; }
        public Nullable<double> LatS { get; set; }
        public Nullable<double> HmslS { get; set; }
        public Nullable<double> VelN { get; set; }
        public Nullable<double> VelE { get; set; }
        public Nullable<double> VelD { get; set; }
        public Nullable<double> HDOP { get; set; }
    
        public virtual DroneLogEntry DroneLogEntry { get; set; }
    }
}
