//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneGP
    {
        public int GPSId { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<double> HeightMSL { get; set; }
        public Nullable<double> HDOP { get; set; }
        public Nullable<double> PDOP { get; set; }
        public Nullable<double> SAcc { get; set; }
        public Nullable<int> NumGPS { get; set; }
        public Nullable<int> NumGLNAS { get; set; }
        public Nullable<int> NumSV { get; set; }
        public Nullable<double> VelN { get; set; }
        public Nullable<double> VelE { get; set; }
        public Nullable<double> VelD { get; set; }
    
        public virtual DroneLogEntry DroneLogEntry { get; set; }
    }
}
