//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneRC
    {
        public int RCId { get; set; }
        public string FailSafe { get; set; }
        public string DataLost { get; set; }
        public string AppLost { get; set; }
        public string ModeSwitch { get; set; }
    
        public virtual DroneLogEntry DroneLogEntry { get; set; }
    }
}
