//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneIMU_ATTI
    {
        public int IMU_ATTI_Id { get; set; }
        public Nullable<double> GPS_H { get; set; }
        public Nullable<double> Roll { get; set; }
        public Nullable<double> Pitch { get; set; }
        public Nullable<double> Yaw { get; set; }
        public Nullable<double> DistanceTravelled { get; set; }
        public Nullable<double> MagDirectionOfTravel { get; set; }
        public Nullable<double> TrueDirectionOfTravel { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> VelComposite { get; set; }
    
        public virtual DroneLogEntry DroneLogEntry { get; set; }
    }
}
