//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCPError
    {
        public int GCPErrorId { get; set; }
        public Nullable<double> GCPMeanError_x { get; set; }
        public Nullable<double> GCPMeanError_y { get; set; }
        public Nullable<double> GCPMeanError_z { get; set; }
        public Nullable<double> GCPSigma_x { get; set; }
        public Nullable<double> GCPSigma_y { get; set; }
        public Nullable<double> GCPSigma_z { get; set; }
        public Nullable<double> GCPRMS_x { get; set; }
        public Nullable<double> GCPRMS_y { get; set; }
        public Nullable<double> GCPRMS_z { get; set; }
    
        public virtual QualityReport QualityReport { get; set; }
    }
}
