//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uncertainty
    {
        public int UncertaintyId { get; set; }
        public Nullable<double> AMU_x { get; set; }
        public Nullable<double> AMU_y { get; set; }
        public Nullable<double> AMU_z { get; set; }
        public Nullable<double> ASU_x { get; set; }
        public Nullable<double> ASU_y { get; set; }
        public Nullable<double> ASU_z { get; set; }
        public Nullable<double> RMU_x { get; set; }
        public Nullable<double> RMU_y { get; set; }
        public Nullable<double> RMU_z { get; set; }
        public Nullable<double> RSU_x { get; set; }
        public Nullable<double> RSU_y { get; set; }
        public Nullable<double> RSU_z { get; set; }
    
        public virtual QualityReport QualityReport { get; set; }
    }
}
